### ISSUE TITLE
Organisation avatar

### ISSUE THREAD

**Issue by colingourlay** [abcnews/meta#1]
News had a rebrand. Let's stick to it.

The quickest win is to just use the highest resolution square icon from the mobile site:

![image](https://cloud.githubusercontent.com/assets/66612/26668098/823da32c-46eb-11e7-96b4-6f2ab6d15a10.png)

**Comment by drzax** [comment]
I'm all for that, but what is the repo?

**Comment by colingourlay** [comment]
Sorry - I just meant for this org's avatar, not a specific repo.

**Comment by drzax** [comment]
Cool—done.
